### ISSUE TITLE
422 Unprocessable Entity - Error

### ISSUE THREAD

**Issue by arturodrt** [laurauzcategui/fastapi_ml_stablediffusion#6]
Hello,

I'm trying to run the code, but once I try to generate the image after filling the fields, I get the following error:

INFO:     None:0 - "GET /api/generate/?prompt=space&num_inference_steps=10&guidance_scale=7.5&seed= HTTP/1.1" 422 Unprocessable Entity

And also I get the error "Oops! Something went wrong generating the image".

Any idea why this could be happening?

**Comment by arturodrt** [comment]
Apparently the problem was related to the following error:
Pipelines loaded with `torch_dtype=torch.float16` cannot run with `cpu` device. It is not recommended to move them to `cpu` as running them will fail. Please make sure to use an accelerator to run the pipeline in inference, due to the lack of support for`float16` operations on this device in PyTorch. Please, remove the `torch_dtype=torch.float16` argument, or use another device for inference.

I changed  torch_dtype=torch.float32 and now it is working.

**Comment by laurauzcategui** [comment]
Hi @Artuurodrt , 

Thanks for reporting it but also looking into it. 

I’ll check what I need to change to make it better too. 

Cheers, 
Laura
